### ISSUE TITLE
单向好友列表有内容但信息为空

### ISSUE THREAD

**Issue by traceless0929** [DeepOceanSoft/Sora#42]
**使用环境**
 -  框架版本号:`v1.0.0-rc20`
 -  运行环境:`gocq v1.0.0-beta7-fix1.  CentOS 7.6.1810 x86_64(Py3.7.9)`

**bug描述**

如图，看到有获取单向好友的接口，于是想查看下单向好友列表，最后数量是22个但是里面的数据都是null

**如何复现**

**错误截图或日志**
![image](https://user-images.githubusercontent.com/12078678/133880749-a342819b-6cc2-47c9-a7c4-3a04bd1df8e9.png)
![image](https://user-images.githubusercontent.com/12078678/133880780-c60dccb9-cfe4-4c22-ba5b-3188bffa9f72.png)
![image](https://user-images.githubusercontent.com/12078678/133880757-b7db6164-6756-4b47-8e3e-a7748a2713fc.png)

**Comment by Yukari316** [comment]
可以给出`gocq`发送的json内容吗
因为我这边是直接加的api
没有单向好友，看不到实际的json内容

**Comment by traceless0929** [comment]
在哪里可以拿到gocq的发送内容json

**Comment by Yukari316** [comment]
啊。。框架里拿不到，只能中间弄个代理什么的（）
不过log服务会在下一个版本里重写了(摸了)

**Comment by Yukari316** [comment]
不过log服务会在下一个版本里重写了

**Comment by Yukari316** [comment]
新版本log可以看json内容了
等CI自动发布更新版本就好了，不过新版本有很多破坏性更新

**Comment by traceless0929** [comment]
> 新版本log可以看json内容了
> 等CI自动发布更新版本就好了，不过新版本有很多破坏性更新

在适配了 果然非常破坏性

**Comment by traceless0929** [comment]
> 新版本log可以看json内容了
> 等CI自动发布更新版本就好了，不过新版本有很多破坏性更新

需要如何配置日志才能开启gocq的json内容记录

**Comment by Yukari316** [comment]
其实是框架的log日志等级设置为debug就可以了

**Comment by traceless0929** [comment]
> 其实是框架的log日志等级设置为debug就可以了

[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Socket]Get json message:{"font":0,"message":[{"data":{"text":"查单向"},"type":"text"}],"message_id":74887391,"message_type":"private","post_type":"message","raw_message":"查单向","self_id":3422096587,"sender":{"age":0,"nickname":"return true;","sex":"unknown","user_id":415206409},"sub_type":"friend","target_id":3422096587,"time":1633748582,"user_id":415206409}
[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Sora]Private msg return true;(415206409) <- 查单向
[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Sora]Parsing msg list
[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Sora]Get msg len=1
[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Sora]Sending get_unidirectional_friend_list request
[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Socket]Get json message:{"data":[{"nickname":"阿飘??( ?? )??","source":"QQ群","user_id":578521375},{"nickname":"豆浆","source":"QQ群","user_id":395966044},{"nickname":"云淡风轻","source":"QQ群","user_id":2481269215},{"nickname":"胡先森","source":"QQ群","user_id":5136410},{"nickname":"虞","source":"QQ群","user_id":191162036},{"nickname":"　","source":"QQ群","user_id":277258687},{"nickname":"　　　　　　　　　　　　","source":"QQ群","user_id":289340062},{"nickname":"云醴","source":"QQ群","user_id":353152888},{"nickname":"难绘深渊有渔火","source":"QQ群","user_id":541596191},{"nickname":"名字好听又不能吃","source":"QQ群","user_id":595260996},{"nickname":"XeinX","source":"QQ群","user_id":634011645},{"nickname":"白墨","source":"QQ群","user_id":793886125},{"nickname":"QQ好友","source":"QQ群","user_id":815904834},{"nickname":"爸爸","source":"QQ群","user_id":931677135},{"nickname":"苍爹，燕云惊","source":"QQ群","user_id":1061709035},{"nickname":"枫叶满山红","source":"QQ群","user_id":1253819896},{"nickname":"给老子爬","source":"QQ群","user_id":1272573687},{"nickname":"กูชอบมึง","source":"QQ群","user_id":1309540538},{"nickname":"霸道总裁李二狗","source":"QQ群","user_id":1550969926},{"nickname":"倾幽诺梦","source":"QQ群","user_id":1835621441},{"nickname":"不见","source":"QQ群","user_id":2904784308},{"nickname":"🍋","source":"QQ群","user_id":2998546526}],"echo":"f48a6533-d18e-45dd-bd7f-c5e3ffe025d0","retcode":0,"status":"ok"}
[{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null},{"nickname":null,"user_id":0,"source":null}]
[40m[37mdbug[39m[22m[49m: OneBot.CommandRoute.Utils.YukariToolBoxLogger[0]
      [Sora|ReactiveApiManager]Get api response {"data":[{"nickname":"阿飘??( ?? )??","source":"QQ群","user_id":578521375},{"nickname":"豆浆","source":"QQ群","user_id":395966044},{"nickname":"云淡风轻","source":"QQ群","user_id":2481269215},{"nickname":"胡先森","source":"QQ群","user_id":5136410},{"nickname":"虞","source":"QQ群","user_id":191162036},{"nickname":"　","source":"QQ群","user_id":277258687},{"nickname":"　　　　　　　　　　　　","source":"QQ群","user_id":289340062},{"nickname":"云醴","source":"QQ群","user_id":353152888},{"nickname":"难绘深渊有渔火","source":"QQ群","user_id":541596191},{"nickname":"名字好听又不能吃","source":"QQ群","user_id":595260996},{"nickname":"XeinX","source":"QQ群","user_id":634011645},{"nickname":"白墨","source":"QQ群","user_id":793886125},{"nickname":"QQ好友","source":"QQ群","user_id":815904834},{"nickname":"爸爸","source":"QQ群","user_id":931677135},{"nickname":"苍爹，燕云惊","source":"QQ群","user_id":1061709035},{"nickname":"枫叶满山红","source":"QQ群","user_id":1253819896},{"nickname":"给老子爬","source":"QQ群","user_id":1272573687},{"nickname":"กูชอบมึง","source":"QQ群","user_id":1309540538},{"nickname":"霸道总裁李二狗","source":"QQ群","user_id":1550969926},{"nickname":"倾幽诺梦","source":"QQ群","user_id":1835621441},{"nickname":"不见","source":"QQ群","user_id":2904784308},{"nickname":"🍋","source":"QQ群","user_id":2998546526}],"echo":"f48a6533-d18e-45dd-bd7f-c5e3ffe025d0","retcode":0,"status":"ok"}

**Comment by Yukari316** [comment]
已经修复，请等待版本更新

**Comment by traceless0929** [comment]
👌🏻
