### ISSUE TITLE
v1.0.0-rc28及以上版本的Log工具类无法在CentOS 8上使用

### ISSUE THREAD

**Issue by qingyu-sama** [DeepOceanSoft/Sora#45]
**使用环境**
 -  框架版本号:v1.0.0-rc28及以上
 -  运行环境:CentOS 8.2

**bug描述**
v1.0.0-rc28及以上版本时调用Log工具类不会在控制台有任何输出

**如何复现**
当我从v1.0.0-rc27及以下版本更换为更高版本时Log工具类失效
应该是因为更改了NuGet包导致的
v1.0.0-rc28及以上版本的YukariToolBox版本为 3.0.8
而v1.0.0-rc27及以下版本YukariToolBox版本为 2.0.0

**错误截图或日志**
v1.0.0-rc28及以上
![image](https://user-images.githubusercontent.com/59732362/142159250-fcb717e3-27c3-415a-a087-01a56646d7c9.png)

v1.0.0-rc27及以下
![image](https://user-images.githubusercontent.com/59732362/142159375-791028fa-12d4-482e-9113-43d386d891f8.png)

**Comment by Yukari316** [comment]
新版本的log服务会默认关闭控制台的输出
请使用以下代码进行设置
> 文档还没来得及改，会在后续补上
```csharp
//设置log
Log.LogConfiguration
   .EnableConsoleOutput() //启用控制台输出
   .SetLogLevel(LogLevel.Debug); //设置log等级
```

**Comment by qingyu-sama** [comment]
好的，谢谢解答

**Comment by Yukari316** [comment]
如果可以的话可以帮忙写写文档（
![99166F8D1BE585BDB8586CE07E0A43E9](https://user-images.githubusercontent.com/7535224/104095113-0f66c280-52d0-11eb-902f-0eaaabdc8e90.jpg)

**Comment by qingyu-sama** [comment]
也可以，有什么开发群之类的地方吗
![-60c5534a06e89259](https://user-images.githubusercontent.com/59732362/142178575-d6ec6cc0-7c69-46bc-9b99-c913966c5c49.jpg)

**Comment by Yukari316** [comment]
日志等级改为debug就能看到了哦
~~虽说群里也没什么人说话（也许就没几个人用C#）~~
