### ISSUE TITLE
SoraCommand设置SourceFlag.Private时提示不支持的类型

### ISSUE THREAD

**Issue by ghost** [DeepOceanSoft/Sora#52]
**使用环境**
 -  框架版本号:`1.0.0-rc.41`
 -  运行环境:`linux docker`

**bug描述**
`SoraCommand`设置`SourceFlag.Private`时提示不支持的类型。
经检查应该是`CommandUtils.cs`的`CheckMethodLegality`的条件判断出现问题。

`if (commandAttr.SourceType is not SourceFlag.Group or SourceFlag.Private)`
`        {`
`            Log.Warning("CommandCheck", $"指令{method.Name}设置了不支持的消息源类型({commandAttr.SourceType}),已自动忽略");`
`            return false;`
`        }`
PS:
这段代码下面返回的代码好像也有错误，因为没能运行到那边，所以我不太确定，
两个消息类型都是`para.ParameterType == typeof(GroupMessageEventArgs)`

**如何复现**
使用`service.Event.CommandManager.MappingCommands`加载带有`SoraCommand`的dll
`SoraCommand`的`SourceType`设置为`Sora.Enumeration.SourceFlag.Private`

**错误截图或日志**
02/01/2022 11:20:00| Warning | Sora.Command.CommandUtils
[CommandCheck]指令TestCommand设置了不支持的消息源类型(Private),已自动忽略

**Comment by Yukari316** [comment]
已修复请等待CI完成新版本发布

**Comment by ghost** [comment]
好的，麻烦大大了
