### ISSUE TITLE
关于异常捕获

### ISSUE THREAD

**Issue by wzddong** [DeepOceanSoft/Sora#53]
报错能否取消发送到私聊和群消息  只打印错误日志，或者改成配置或者加debug模式才发群
![M2{MQ X$XI03EUGYK EWD~F](https://user-images.githubusercontent.com/30207313/153362389-0effc972-bc3a-485f-8775-b64db0694b90.png)

**Comment by Yukari316** [comment]
可以的，之后会作为新的设置选项写入到框架中
