### ISSUE TITLE
收到邀请进群通知后崩溃

### ISSUE THREAD

**Issue by senioi** [DeepOceanSoft/Sora#68]
**使用环境**
 -  框架版本号: 1.0.0-rc73``
 -  运行环境: Linux``

**bug描述**
如果机器人被任何人邀请加入群后就会出现崩溃.

**如何复现**
如果机器人被任何人邀请加入群后就会出现崩溃.

**错误截图或日志**
![image](https://user-images.githubusercontent.com/42415346/179712528-ab5a8f19-7fc4-46f2-b960-850e9fc6df9a.png)

**Comment by Yukari316** [comment]
从错误的日志里可以看到你的 `gocq` 设置了 `string` 的上报格式，请认真阅读文档再发起issue
以及，请将错误日志复制粘贴后以代码格式粘贴至issue以方便阅读
相同的issue将会被我关闭
