### ISSUE TITLE
监听群员变动事件后被拉入新群后崩溃

### ISSUE THREAD

**Issue by senioi** [DeepOceanSoft/Sora#69]
**使用环境**
 -  框架版本号:1.0.0-rc73``
 -  运行环境: Linux``

**bug描述**
使用示例代码 **service.Event.OnGroupMemberChange += async (_, eventArgs) =>**
监听群员变动事件后,Sora报错崩溃

**如何复现**
监听群员变动事件后,使用一个新群(人数低于10)邀请机器人加群,然后崩溃.

**错误截图或日志**
![image](https://user-images.githubusercontent.com/42415346/179723102-3274ff75-5370-4c29-b85f-6c92dd6b125f.png)

**Comment by Yukari316** [comment]
复现失败
请检查gocq数据格式设置
