### ISSUE TITLE
依旧是关于SoraCommand中的MatchType

### ISSUE THREAD

**Issue by hd80606b** [DeepOceanSoft/Sora#70]
这里，提出新的bug，依旧是关于SoraCommand中的MatchType
在这个改过后的版本1.0.0-rc.73
现在KeyWord匹配变成了：只要出现其中一个字就会匹配
举例：依旧指南的例子，添加MatchType = Sora.Enumeration.MatchType.KeyWord 来匹配 坏耶
然而，你发送：“太坏了”，“坏”，“我觉得这个好耶”，“耶”
机器人就会回复“好耶”

**Comment by Yukari316** [comment]
这几天事情比较多，会抽时间修一下
~~我是不是不适合写正则~~

**Comment by hd80606b** [comment]
我把CommandUtils.cs里的151行和185行$`"({command})+"`改成了`$"({command}{1}"`
就解决了问题，至于解决问题的原理...答不上来，但我知道+是匹配1或者多次改成{1}就变成只匹配1次了，做关键词匹配 匹配一次就好了，莫名解决了这个问题
~~我这也是业余水平，遇到要正则就去一个个试~~
~~反编译dll再打包回去测的~~

**Comment by Yukari316** [comment]
我今晚更新一个看看
~~可以的话可以来群里坐坐~~

**Comment by hd80606b** [comment]
在日志Debug中所展示的群号，已经搜不到了（

**Comment by Yukari316** [comment]
草我忘记开检索了，再试试
~~之前有奇怪的人~~

**Comment by Yukari316** [comment]
似乎没有复现出来...
![K1%LG649 4R)}ZA~(SH91H4](https://user-images.githubusercontent.com/7535224/180845682-ec5ec406-1474-46aa-ae4d-ab04dcb7b6d3.png)
![image](https://user-images.githubusercontent.com/7535224/180845714-1898fb21-d4f5-473f-b0cf-ac375879d180.png)
