### ISSUE TITLE
Group.GetEssenceMsgList() 精华消息获取的2个问题

### ISSUE THREAD

**Issue by buger404** [DeepOceanSoft/Sora#84]
**使用环境**
 -  框架版本号:`1.3.0`
 -  运行环境:`Windows`

**bug描述**
`Group.GetEssenceMsgList()`在任何群，机器人身份为群主、管理员或普通成员时，均返回`ApiStatusType.Ok`，但获取精华消息数始终为0。

**如何复现**
调用'Group.GetEssenceMsgList()'

**错误截图或日志**
无

**Comment by buger404** [comment]
这边发现是协议问题，切换到iPad协议可以正常获取。
但是希望协议不支持的情况下不应返回`ApiStatusType.Ok`，这里遇到了新的问题：
* 只能获取最新的20个精华消息。
* 精华消息的消息ID为`long`类型，`SoraApi.GetMessage()`要求参数为`int`类型，强制转换可成功获取部分消息内容，但大部分则会失败，猜测是此处类型不匹配的问题。

**Comment by buger404** [comment]
对于问题：
* 精华消息的消息ID为long类型，SoraApi.GetMessage()要求参数为int类型，强制转换可成功获取部分消息内容，但大部分则会失败，猜测是此处类型不匹配的问题。

我查看了go-cqhttp的文档：[api-获取精华消息列表](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%B2%BE%E5%8D%8E%E6%B6%88%E6%81%AF%E5%88%97%E8%A1%A8)

这里`message_id`的类型为`int32`，而此处代码：
https://github.com/Hoshikawa-Kaguya/Sora/blob/0727fd494d60cc05cf8ae067783176fc4e519d94/Sora/Entities/Info/EssenceInfo.cs#L15
https://github.com/Hoshikawa-Kaguya/Sora/blob/0727fd494d60cc05cf8ae067783176fc4e519d94/Sora/Entities/Info/EssenceInfo.cs#L49

为`int64`类型，可能有误。

虽然这样看来可能消息获取失败与类型不匹配关系不大。

**Comment by buger404** [comment]
对于问题：

* 只能获取最新的20个精华消息。

已提交Issue至Mrs4s/go-cqhttp：https://github.com/Mrs4s/go-cqhttp/issues/2086

**Comment by Yukari316** [comment]
不急我周末看下，平时有点忙

**Comment by buger404** [comment]
好的！还有个小问题是，获取群公告的时候，公告附带的图片的width、height的值可能为空字符串(这里实测发现比较老的群公告会有这种情况)
导致`ToObject<List<GroupNoticeInfo>>()`发生错误崩溃。

**Comment by Yukari316** [comment]
好的到时候看看

**Comment by Yukari316** [comment]
之前比较忙我抽空看了一下
- 精华消息的问题，这边我msgid是int64不太可能出现转换的问题应该是gocq那边的问题，不过我会把类型也改成int32省的拿出来再二次转换
- 公告这边我修一下
