### ISSUE TITLE
接收消息时出现错误 MSG_NOT_FOUND

### ISSUE THREAD

**Issue by ghost** [DeepOceanSoft/Sora#86]
**使用环境**
 -  框架版本号:`1.3.3`
 -  运行环境:`linux docker`

**bug描述**
使用cqhttp目前最新的dev版本后，每次有人发消息都会出现一条错误。
不过功能还是可以正常使用。

**如何复现**
接收QQ消息

**错误截图或日志**
![QQ截图20230804010234](https://github.com/Hoshikawa-Kaguya/Sora/assets/85502450/137de595-afae-4a9f-a25d-6f3bc5f58ba3)

**Comment by Yukari316** [comment]
api的报错是找不到id对应信息，可能是`gocq`的数据库失效的问题 （gocq的数据库负责储存信息上下文）
这个是`自动标记消息已读`的功能的报错，请确认一下`gocq`的数据库是启用并且是能够正常使用的
如果数据库是正常的那么请等待`dev`版本的正式发版，因为`Sora`是在`gocq`正式发版后才能跟进开发的

如果不想看到这个报错，可以在构建`ISoraService`的时候关闭`AutoMarkMessageRead`的功能
这个功能是用于避免`gocq`重复发送消息的，关闭后对正常运行的影响并不大

如果可以的话请提供一下`gocq`的**Debug**日志，并且提供所使用的`gocq` `dev`分支的**commit hash**或者**链接**

**Comment by ghost** [comment]
感谢大大回复，可能是gocq版本问题，反正也不影响使用就先继续用，等最新正式版了。
debug日志我没开启所以没有，版本是actions里docker最新的[3b99a82]

**Comment by Yukari316** [comment]
![image](https://github.com/Hoshikawa-Kaguya/Sora/assets/7535224/fb898ce0-88ff-4a47-8c04-f7ee92034655)
我今天调试bot的时候没有遇到你说的那个问题，我的gocq版本是[5db03c7](https://github.com/Mrs4s/go-cqhttp/commit/5db03c7092de22b01452117c9af589948cce83ff)
估计是你的gocq数据库失效了
