### ISSUE TITLE
转发消息的时候图片会变成cq码

### ISSUE THREAD

**Issue by maxzhang666** [DeepOceanSoft/Sora#89]
**使用环境**
 -  框架版本号:`1.4.1`
 -  运行环境:`docker`

**bug描述**
详细描述bug的内容
进行消息转发的时候图片会变成cq码

**如何复现**
```
e.Reply(e.Message.MessageBody);
```

**错误截图或日志**
<img width="678" alt="image" src="https://github.com/Hoshikawa-Kaguya/Sora/assets/10149878/ab75bfd1-c155-4744-bf06-7542e88c59ab">

**Comment by maxzhang666** [comment]
最开始是1.3.0的时候有这个情况，尝试升级1.4.1之后问题仍然存在

**Comment by Yukari316** [comment]
无法复现，请检查gocq的上报格式或者图片链接是否合法
![image](https://github.com/Hoshikawa-Kaguya/Sora/assets/7535224/ae5b71d8-7972-4df4-b856-8af3509c5e0e)
![image](https://github.com/Hoshikawa-Kaguya/Sora/assets/7535224/00c757a6-fbd7-4a27-992c-2cc6e67871aa)

**Comment by maxzhang666** [comment]
gocqhttp里的消息肯定是错的了，gocqhttp用的是docker的dev版本
断点看到的cq码的图片地址就有异常，自己构造图片消息的话发送是正常的

把收到的MessageBody直接发出去就会有下面的问题

`&`被Unicode编码了
我是复读图片消息出现的
<img width="1637" alt="image" src="https://github.com/Hoshikawa-Kaguya/Sora/assets/10149878/e12b18af-96e9-498d-ae2a-705eced501fa">
复现代码
<img width="497" alt="image" src="https://github.com/Hoshikawa-Kaguya/Sora/assets/10149878/5073bf78-1ba6-4433-9313-c05f444c98f8">

**Comment by Yukari316** [comment]
![image](https://github.com/Hoshikawa-Kaguya/Sora/assets/7535224/dca44497-76c3-45d5-9788-38813a15be46)
![image](https://github.com/Hoshikawa-Kaguya/Sora/assets/7535224/d2e6391f-a19e-4e10-ac5c-a8a2badba07e)
复读图片也没出现问题啊
我这的gocq用的是dev分支最新的CI构建版本[f16d72f](https://github.com/Mrs4s/go-cqhttp/commit/f16d72f0ca48b3ee003016398cb93143be2a0cc4)
qsign为`1.1.9`的docker镜像

**Comment by maxzhang666** [comment]
真是离谱

我在测测、、、、

**Comment by maxzhang666** [comment]
懵了、、、

<img width="528" alt="image" src="https://github.com/Hoshikawa-Kaguya/Sora/assets/10149878/f5c06095-8a24-4275-8acb-96f12164c176">

<img width="632" alt="image" src="https://github.com/Hoshikawa-Kaguya/Sora/assets/10149878/804522b7-6e3c-4fc4-8027-2a3e0eca3f82">

**Comment by maxzhang666** [comment]
又去gocqhttp看了看   大概是机器人那边的兼容问题

我是Mac NTQQ发送的图片

https://github.com/Mrs4s/MiraiGo/issues/341

**Comment by maxzhang666** [comment]
非SDK问题，到这吧先

感谢

**Comment by Yukari316** [comment]
也有可能是图片格式的之类的问题，你可以去试试gocq ci的最新构建版本

**Comment by maxzhang666** [comment]
> 也有可能是图片格式的之类的问题，你可以去试试gocq ci的最新构建版本

我这边测试MacQQ发送的图片转发有问题

手机QQ跟Win的QQ就正常、、、
